### ISSUE TITLE
cornerRadius ignored coming back to the original state

### ISSUE THREAD

**Issue by malcommac** [AladinWay/TransitionButton#3]
`cornerRadius` property is not restored to user custom value when coming back to the original state (ie. stopping animation with shake).

I've fixed it by adding `self.layer.cornerRadius = self.cornerRadius` to the last line of `setOriginalState()` func.

```swift
private func setOriginalState() {
        self.animateToOriginalWidth()
        self.spiner.stopAnimation()
        self.setTitle(self.cachedTitle, for: .normal)
        self.setImage(self.cachedImage, for: .normal)
        self.isUserInteractionEnabled = true // enable again the user interaction
	self.layer.cornerRadius = self.cornerRadius
}
```

Hope you will add it to the main branch asap.
Have a nice day and thank you for your work.

**Comment by AladinWay** [comment]
@malcommac Thank you for using the library. I will take a look and publish an update by tomorrow if needed. Have a nice day :)

**Comment by AladinWay** [comment]
@malcommac  As promised, the issue is fixed now in version 0.2.0

**Comment by otymartin** [comment]
@AladinWay issue still persists in 0.2.0.
Never mind didnt know TransitionButton had a `cornerRadius` property.

**Comment by JockerGG** [comment]
Hello! 
Your library is awesome! thanks for this. 

In the version 0.3.0 i have the same problem to the cornerRadius, i fixed this problem modifying the `open func startAnimation()`, here is the function now: 

![image](https://user-images.githubusercontent.com/6700974/38050268-a9c28e02-3287-11e8-8808-5343976e9182.png)

I adding the line `self.cornerRadius = self.layer.cornerRadius` because the cornerRadius always is 0. 

Have nice day and thanks for this work!
